#!/usr/bin/env python
"""
Problem 45
06 June 2003
 
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle        T_n=n(n+1)/2    1, 3, 6, 10, 15, ...
                                 +2  +3 +4  +5
Pentagonal      P_n=n(3n-1)/2   1, 5, 12, 22, 35, ...
                                 +4  +7  +10 +13
Hexagonal       H_n=n(2n-1)     1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Answer: ?????
"""

import gmpy
import itertools

def hexagonal(n):
    return n*(2*n-1)

def is_pentagonal(x):
    """Number x is pentagonal if (sqrt(24x+1) + 1) / 6 is natural"""
    root = 24*x+1
    if gmpy.is_square(root):
        return 0 == (int(root**0.5) + 1) % 6
        #if 0 == (int(root**0.5) + 1) % 6:
        #    print (int(root**0.5) + 1) / 6
        #    return True
    return False

def solve():
    # TODO: Can be speed up with a step of gcd(165,143)
    for n in itertools.count(144):
        # All hexagonal numbers are triangle numbers.
        # Only need to test for pentagonal numbers.
        if is_pentagonal(hexagonal(n)):
            #print n
            return hexagonal(n)

if __name__ == '__main__':
    print "Answer: %s" % solve()

