#!/usr/bin/env python
"""
Problem 2
19 October 2001
 
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed
four million.

Answer: ?????
"""

#TODO: Put this in a sequences module
def fib(max):
    """Fibonacci sequence generator"""
    a, b = 1, 2
    while a <= max:
        yield a
        a, b = b, a+b

def solve():
    return sum([f for f in fib(4000000) if 0 == f % 2])
 
if __name__ == '__main__':
    print "Answer:", solve()

